SELECT DATABASE() INTO @DBNAME;
SET @FROMTABLE = 'table1';
SET @TOTABLE = 'copy_of_table1';

-- Creating the table
SET @QUERYSTRING = CONCAT('CREATE TABLE ', @TOTABLE, ' LIKE ', @FROMTABLE, ';');
PREPARE PREPAREDQUERY from @QUERYSTRING;
EXECUTE PREPAREDQUERY;
DEALLOCATE PREPARE PREPAREDQUERY;
-- ~

-- Getting the old table's auto increment value
SET @QUERYSTRING = CONCAT('SELECT `AUTO_INCREMENT` INTO @AIVALUE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = \'', @DBNAME, '\' AND TABLE_NAME = \'', @FROMTABLE, '\';');
PREPARE PREPAREDQUERY from @QUERYSTRING;
EXECUTE PREPAREDQUERY;
DEALLOCATE PREPARE PREPAREDQUERY;
-- ~

-- Setting the new table's auto increment value
SET @QUERYSTRING = CONCAT('ALTER TABLE ', @TOTABLE, ' AUTO_INCREMENT = ', @AIVALUE, ';');
PREPARE PREPAREDQUERY from @QUERYSTRING;
EXECUTE PREPAREDQUERY;
DEALLOCATE PREPARE PREPAREDQUERY;
-- ~
